global:
    scrape_interval:     15s
    evaluation_interval: 15s
rule_files:
scrape_configs:
- job_name: 'jmx'
  static_configs:
  - targets: ['jmx-exporter:5556']
- job_name: 'kafka-exporter'
  static_configs:
  - targets: ['kafka-exporter:5556']