global:
    scrape_interval:     15s
    evaluation_interval: 15s
rule_files:
scrape_configs:
- job_name: 'kafka-exporter'
  static_configs:
  - targets: ['kafka-exporter:9308']
- job_name: 'kafka-jmx'
  static_configs:
  - targets: ['broker:9998']